import { useState } from 'react';
import { Send, FileText, Check, AlertTriangle, Mail, User, Lock, Smartphone, Link as LinkIcon } from 'lucide-react';
import { useAgentProgress } from '../hooks/useAgentProgress';

type ScamType = 'Phishing (Email)' | 'Smishing (SMS)' | 'Vishing (Voice)' | 'Tech Support' | 'Investment Fraud' | 'Other';

export default function Dispatcher() {
  const { incrementStat } = useAgentProgress();
  const [formData, setFormData] = useState({
    scamType: 'Phishing (Email)' as ScamType,
    offender: '',
    evidence: '',
    description: ''
  });
  
  const [copied, setCopied] = useState(false);

  const scamTypes: { value: ScamType; icon: any }[] = [
    { value: 'Phishing (Email)', icon: Mail },
    { value: 'Smishing (SMS)', icon: Smartphone },
    { value: 'Vishing (Voice)', icon: PhoneIcon }, // Defined below for simplicity
    { value: 'Tech Support', icon: User },
    { value: 'Investment Fraud', icon: Lock },
    { value: 'Other', icon: AlertTriangle },
  ];

  const generateReportBody = () => {
    return `OFFICIAL SCAM REPORT
--------------------------------
TYPE: ${formData.scamType}
OFFENDER ID: ${formData.offender || 'Unknown'}
DATE: ${new Date().toLocaleDateString()}

EVIDENCE / LINKS:
${formData.evidence}

DESCRIPTION:
${formData.description}

Report generated by ScamSherlock.`;
  };

  const handleCopy = async () => {
    const text = generateReportBody();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    incrementStat('reportsSent', 1);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleMailTo = () => {
     incrementStat('reportsSent', 1);
  };

  const getMailToLink = () => {
    const subject = encodeURIComponent(`Scam Report: ${formData.scamType}`);
    const body = encodeURIComponent(generateReportBody());
    // Using widely accepted reporting address; users can change TO field
    return `mailto:reportphishing@apwg.org?subject=${subject}&body=${body}`;
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fade-in-up pb-20">
      {/* Header */}
      <div className="space-y-4">
        <div className="flex items-center gap-4 mb-2">
            <div className="p-3 bg-trenchcoat/10 rounded-xl border border-trenchcoat/20">
                <Send className="w-8 h-8 text-trenchcoat" />
            </div>
            <h1 className="text-4xl md:text-5xl font-sherlock font-bold tracking-tight text-white">
            The <span className="text-trenchcoat">Dispatcher</span>
            </h1>
        </div>
        <p className="text-text-secondary text-lg max-w-3xl leading-relaxed ml-1">
          Take action. Compile your evidence into a formal incident report and dispatch it 
          directly to cybercrime authorities.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* REPORT FORM */}
        <div className="space-y-6">
            <div className="bg-white/5 border border-white/10 rounded-xl p-6 space-y-6 backdrop-blur-md">
                <h3 className="text-xl font-bold font-sherlock text-text-primary border-b border-white/10 pb-4">
                    Incident Details
                </h3>

                {/* Scam Type */}
                <div className="space-y-2">
                    <label className="text-sm font-mono text-trenchcoat uppercase tracking-wider">Scam Category</label>
                    <div className="grid grid-cols-2 gap-2">
                        {scamTypes.map((type) => (
                            <button
                                key={type.value}
                                onClick={() => setFormData({...formData, scamType: type.value})}
                                className={`flex items-center gap-2 p-3 rounded-lg border text-sm transition-all ${
                                    formData.scamType === type.value
                                    ? 'bg-trenchcoat/20 border-trenchcoat text-trenchcoat font-bold'
                                    : 'bg-noir-bg border-white/5 text-text-secondary hover:bg-white/5'
                                }`}
                            >
                                <type.icon className="w-4 h-4" />
                                <span className="truncate">{type.value.split(' ')[0]}</span>
                            </button>
                        ))}
                    </div>
                </div>

                {/* Offender Info */}
                <div className="space-y-2">
                    <label className="text-sm font-mono text-trenchcoat uppercase tracking-wider">Offender Contact (Email/Phone)</label>
                    <div className="relative">
                        <User className="absolute left-3 top-3 w-5 h-5 text-white/30" />
                        <input 
                            type="text" 
                            className="w-full bg-noir-bg border border-white/10 rounded-lg py-3 pl-10 pr-4 text-white focus:border-trenchcoat focus:ring-1 focus:ring-trenchcoat outline-none transition-all placeholder:text-white/20"
                            placeholder="e.g. support@fake-bank.com or +1-555-0199"
                            value={formData.offender}
                            onChange={(e) => setFormData({...formData, offender: e.target.value})}
                        />
                    </div>
                </div>

                {/* Evidence Links */}
                <div className="space-y-2">
                    <label className="text-sm font-mono text-trenchcoat uppercase tracking-wider">Extracted Evidence (URLs)</label>
                    <div className="relative">
                        <LinkIcon className="absolute left-3 top-3 w-5 h-5 text-white/30" />
                        <textarea 
                            className="w-full h-32 bg-noir-bg border border-white/10 rounded-lg py-3 pl-10 pr-4 text-white focus:border-trenchcoat focus:ring-1 focus:ring-trenchcoat outline-none transition-all placeholder:text-white/20 font-mono text-sm resize-none"
                            placeholder="Paste extracted links from The Wiretap here..."
                            value={formData.evidence}
                            onChange={(e) => setFormData({...formData, evidence: e.target.value})}
                        />
                    </div>
                </div>

                 {/* Description */}
                 <div className="space-y-2">
                    <label className="text-sm font-mono text-trenchcoat uppercase tracking-wider">Brief Description</label>
                    <textarea 
                        className="w-full h-24 bg-noir-bg border border-white/10 rounded-lg py-3 px-4 text-white focus:border-trenchcoat focus:ring-1 focus:ring-trenchcoat outline-none transition-all placeholder:text-white/20 resize-none"
                        placeholder="What did they ask for? Did you click anything?"
                        value={formData.description}
                        onChange={(e) => setFormData({...formData, description: e.target.value})}
                    />
                </div>
            </div>
        </div>

        {/* PREVIEW & ACTIONS */}
        <div className="space-y-6">
            <div className="bg-noir-panel border border-trenchcoat/20 rounded-xl p-1 relative overflow-hidden group">
                <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-transparent via-trenchcoat to-transparent opacity-50" />
                
                {/* Generated Report Preview */}
                <div className="bg-noir-bg rounded-lg p-6 font-mono text-sm text-text-secondary leading-relaxed whitespace-pre-wrap overflow-y-auto max-h-[600px] shadow-inner">
                    {generateReportBody()}
                </div>

                {/* Stamp */}
                <div className="absolute bottom-6 right-6 opacity-10 pointer-events-none rotate-[-15deg] border-4 border-trenchcoat rounded-lg p-2">
                    <span className="text-4xl font-sherlock font-bold text-trenchcoat uppercase">DRAFT</span>
                </div>
            </div>

            <div className="flex flex-col gap-3">
                <button 
                    onClick={handleCopy}
                    className="w-full flex items-center justify-center gap-2 py-4 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-white font-bold transition-all group"
                >
                    {copied ? <Check className="w-5 h-5 text-accent-green" /> : <FileText className="w-5 h-5 group-hover:scale-110 transition-transform" />}
                    {copied ? 'Copied to Clipboard' : 'Copy Report Text'}
                </button>

                <a 
                    href={getMailToLink()}
                    onClick={handleMailTo}
                    className="w-full flex items-center justify-center gap-2 py-4 bg-trenchcoat hover:bg-trenchcoat/90 text-noir-bg font-bold font-mono tracking-wider uppercase rounded-lg shadow-lg hover:shadow-trenchcoat/20 transition-all hover:-translate-y-0.5"
                >
                    <Mail className="w-5 h-5" />
                    Dispatch to Authorities
                </a>
                <p className="text-xs text-center text-text-muted mt-2">
                    Opens your default email client with a pre-formatted message to the Anti-Phishing Working Group (reportphishing@apwg.org).
                </p>
            </div>
        </div>
      </div>
    </div>
  );
}

// Simple Phone Icon component since lucide-react Phone might conflict if not imported carefully
function PhoneIcon(props: any) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>
    )
}
